# Configuração do Jekyll para o Caderno Digital

# Informações do site
title: "Caderno Digital - Produção de Conteúdos Multimedia"
description: "Caderno digital simples para a disciplina"
author: "Xavier"
email: "xavierpires2001@gmail.com"

# URL do site (ajustar conforme o repositório GitHub)
url: "https://xavip1299.github.io"
baseurl: "/caderno-digital"

# Configurações Jekyll
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins básicos
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navegação principal
header_pages:
  - aulas.md
  - exercicios.md
  - projeto-final.md
  - recursos.md

# Configurações básicas
github_username: xavip1299