# Configuração Jekyll
title: "Caderno Digital - Produção de Conteúdos Multimedia"
description: "Caderno digital para a disciplina"
author: "Xavier Pires" 
email: "xavierpires2001@gmail.com"

# URLs
url: "https://xavip1299.github.io"
baseurl: "/caderno-digital"

# Jekyll settings
markdown: kramdown
highlighter: rouge
theme: minima
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Configurações de build
show_excerpts: false
minima:
  date_format: "%d/%m/%Y"

# Collections (para usar mais Jekyll)
collections:
  aulas:
    output: true
    permalink: /:collection/:name/
  exercicios:
    output: true  
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_aulas"
      type: "aulas"
    values:
      layout: "page"
  - scope:
      path: "_exercicios"
      type: "exercicios"
    values:
      layout: "page"

# Navegação
header_pages:
  - aulas.md
  - exercicios.md
  - projeto-final.md
  - recursos.md

# Info adicional
github_username: xavip1299
timezone: Europe/Lisbon